// <auto-generated />
namespace MVC_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnsaddedinSalesModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnsaddedinSalesModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202408121024546_columns added in Sales Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
