//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string CarName { get; set; }
        public double CarCost { get; set; }
        public int ManufacturerID { get; set; }
        public int ManufacturerMfrId { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
