//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> DeptNo { get; set; }
        public string Phoneno { get; set; }
        public string remarks { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
